import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

// Cache to avoid repeated calls for the same track
const descriptionCache: Record<string, string> = {
  "Neon Pulse": "A high-octane synthwave journey through a digital metropolis, pulsing with emerald energy.",
  "Cyber Drift": "Late-night neural frequencies designed for high-speed data streams and neon-lit highways.",
  "Digital Void": "A deep, atmospheric descent into the cyan-tinted architecture of the global network."
};

export async function getTrackInfo(trackName: string) {
  // Check cache first
  if (descriptionCache[trackName] && !descriptionCache[trackName].includes("Neural beats")) {
    return descriptionCache[trackName];
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview", // Using flash for better performance and quota
      contents: `Generate a short, cool, futuristic description (max 15 words) for an AI-generated music track titled "${trackName}". Vibe: dark neon, synthwave.`,
    });
    
    const text = response.text?.trim() || "A futuristic soundscape generated by neural networks.";
    descriptionCache[trackName] = text; // Cache the result
    return text;
  } catch (error: any) {
    // Log error but don't crash
    console.warn("Gemini API Quota or Error:", error?.message || error);
    
    // Return a pre-defined fallback if available, otherwise a generic one
    return descriptionCache[trackName] || "Neural beats for the digital age.";
  }
}
